name: Build & Deploy

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Cache
        uses: actions/cache@v2
        with:
          path: Library
          key: library

      - name: Build
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Build
          path: build/WebGL/WebGL

  deploy:
    needs: build
    if: github.ref_type == 'tag'
    permissions:
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: Build

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: .

      - name: Deploy Pages
        id: deployment
        uses: actions/deploy-pages@v1
